services:
  - type: web
    name: skin-disease-backend
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5001
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: skin_ai